import { Urbanist } from 'next/font/google'
// import { JetBrains_Mono } from "next/font/google";
import './globals.css'
import { Providers } from './providers'

const urbanist = Urbanist({
    variable: '--font-urbanist',
    subsets: ['latin'],
})

// const jetbrainsMono = JetBrains_Mono({
//   variable: "--font-jetbrains-mono",
//   subsets: ["latin"],
// });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${urbanist.className} antialiased`} //
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
