spring.application.name=SpringSecurity
spring.security.user.name=Sujit
spring.security.user.password=Rampage

spring.jpa.database=mysql
spring.datasource.url = jdbc:mysql://localhost/myOffice
spring.datasource.username=root
spring.datasource.password=Tirumala123#
spring.jpa.show-sql=true